package com.jcuesoft.cuebridge.bex.service;

import java.util.ArrayList;
import java.util.List;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.jcuesoft.cuebridge.bex.dao.BexToTaekangDAO;
import com.jcuesoft.cuebridge.bex.vo.BexMasterRequestVO;
import com.jcuesoft.cuebridge.bex.vo.BexToTaekangVO;
import com.jcuesoft.cuebridge.common.module.CommonFileUpload;
import com.jcuesoft.cuebridge.common.module.CommonHttpClient;
import com.jcuesoft.cuebridge.common.service.BaseService;
import com.jcuesoft.cuebridge.common.service.CommonBizService;
@Service
public class BexToTaekangService extends BaseService{
    @Autowired
    private CommonBizService commonBizService;    
    @Autowired
    private BexMasterService bexMasterService;
    @Autowired
    private BexToTaekangDAO bexToTaekangDAO;    
    
    String excute(BexMasterRequestVO bexMasterRequestVO) throws Exception{
        logger.debug("Call BexToTaekangService excute");
        String resultCode = ""; //resultCode        
        String imgUrl = "";
        String extDataEncDir = "/ext_data_agency/70305/upload/";
        String nmScreen = "";
        String resultPost = "";
        String resultMemo = "";
        String tmpExt="";
        String nsiExt=".nsi";
        resultCode = "Success";             
        CommonFileUpload commonFileUpload = null;

        logger.debug("Call BexToTaekangService excute getBexMasterNoEx");
        bexMasterRequestVO.setNoEx(commonBizService.getBexMasterNoEx(bexMasterRequestVO.getNoReq()));
        imgUrl = commonBizService.getStCustomerDsImgUrl(bexMasterRequestVO.getCdCooperate());
        logger.debug("Call BexToTaekangService getStCustomerDsImgUrl:"+imgUrl);
        logger.debug("Call BexToTaekangService excute insertBexMaster");
        bexMasterService.insertBexMaster(bexMasterRequestVO);
        logger.debug("Call BexToTaekangService excute insertBexContact");
        bexMasterRequestVO.setNmScreen("접수");
        bexMasterRequestVO.setDsCooperate("최초실행");        
        bexMasterService.insertBexContact(bexMasterRequestVO);
        
        BexToTaekangVO bexToTaekangVO = new BexToTaekangVO();
        bexToTaekangVO = bexToTaekangDAO.getBexToTaekang(bexMasterRequestVO);
        List <NameValuePair> sendParam = new ArrayList <NameValuePair>();
        
        sendParam.add(new BasicNameValuePair("pro_code", bexToTaekangVO.getPro_code()));
        sendParam.add(new BasicNameValuePair("com_code", bexToTaekangVO.getCom_code()));
        //sendParam.add(new BasicNameValuePair("com_code", "starcredit_1"));
        sendParam.add(new BasicNameValuePair("cooperate_code", bexToTaekangVO.getCooperate_code()));
        sendParam.add(new BasicNameValuePair("sub_com_code", bexToTaekangVO.getSub_com_code()));
        sendParam.add(new BasicNameValuePair("name", bexToTaekangVO.getName()));
        sendParam.add(new BasicNameValuePair("ssn11", bexToTaekangVO.getSsn11()));
        sendParam.add(new BasicNameValuePair("ssn12", bexToTaekangVO.getSsn12()));
        sendParam.add(new BasicNameValuePair("app_money", bexToTaekangVO.getApp_money()));
        sendParam.add(new BasicNameValuePair("surety", bexToTaekangVO.getSurety()));
        sendParam.add(new BasicNameValuePair("email", bexToTaekangVO.getEmail()));
        sendParam.add(new BasicNameValuePair("ph21", bexToTaekangVO.getPh21()));
        sendParam.add(new BasicNameValuePair("ph22", bexToTaekangVO.getPh22()));
        sendParam.add(new BasicNameValuePair("ph23", bexToTaekangVO.getPh23()));
        sendParam.add(new BasicNameValuePair("marry", bexToTaekangVO.getMarry()));
        sendParam.add(new BasicNameValuePair("job", bexToTaekangVO.getJob()));
        sendParam.add(new BasicNameValuePair("s_jobtype", bexToTaekangVO.getS_jobtype()));
        sendParam.add(new BasicNameValuePair("s_com", bexToTaekangVO.getS_com()));
        sendParam.add(new BasicNameValuePair("s_tel1", bexToTaekangVO.getS_tel1()));
        sendParam.add(new BasicNameValuePair("s_tel2", bexToTaekangVO.getS_tel2()));
        sendParam.add(new BasicNameValuePair("s_tel3", bexToTaekangVO.getS_tel3()));
        sendParam.add(new BasicNameValuePair("s_date1", bexToTaekangVO.getS_date1()));
        sendParam.add(new BasicNameValuePair("s_date2", bexToTaekangVO.getS_date2()));
        sendParam.add(new BasicNameValuePair("s_class", bexToTaekangVO.getS_class()));
        sendParam.add(new BasicNameValuePair("s_money", bexToTaekangVO.getS_money()));
        sendParam.add(new BasicNameValuePair("s_jobpart", bexToTaekangVO.getS_jobpart()));
        sendParam.add(new BasicNameValuePair("s_hiredtype", bexToTaekangVO.getS_hiredtype()));
             
        if(bexToTaekangVO.getImg_url1() != null && bexToTaekangVO.getImg_url1().trim().length() != 0){
            commonFileUpload = new CommonFileUpload();
        }
        
        if(bexToTaekangVO.getImg_url1() != null && bexToTaekangVO.getImg_url1().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url1(), extDataEncDir+bexToTaekangVO.getImg_file1());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file1());
            sendParam.add(new BasicNameValuePair("img_url1", imgUrl+bexToTaekangVO.getImg_file1().replace(tmpExt, nsiExt)));
        }        
        if(bexToTaekangVO.getImg_url2() != null && bexToTaekangVO.getImg_url2().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url2(), extDataEncDir+bexToTaekangVO.getImg_file2());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file2());
            sendParam.add(new BasicNameValuePair("img_url2", imgUrl+bexToTaekangVO.getImg_file2().replace(tmpExt, nsiExt)));
        }
        if(bexToTaekangVO.getImg_url3() != null && bexToTaekangVO.getImg_url3().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url3(), extDataEncDir+bexToTaekangVO.getImg_file3());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file3());
            sendParam.add(new BasicNameValuePair("img_url3", imgUrl+bexToTaekangVO.getImg_file3().replace(tmpExt, nsiExt)));
        }
        if(bexToTaekangVO.getImg_url4() != null && bexToTaekangVO.getImg_url4().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url4(), extDataEncDir+bexToTaekangVO.getImg_file4());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file4());
            sendParam.add(new BasicNameValuePair("img_url4", imgUrl+bexToTaekangVO.getImg_file4().replace(tmpExt, nsiExt)));
        }
        if(bexToTaekangVO.getImg_url5() != null && bexToTaekangVO.getImg_url5().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url5(), extDataEncDir+bexToTaekangVO.getImg_file5());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file5());
            sendParam.add(new BasicNameValuePair("img_url5", imgUrl+bexToTaekangVO.getImg_file5().replace(tmpExt, nsiExt)));
        }
        if(bexToTaekangVO.getImg_url6() != null && bexToTaekangVO.getImg_url6().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url6(), extDataEncDir+bexToTaekangVO.getImg_file6());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file6());
            sendParam.add(new BasicNameValuePair("img_url6", imgUrl+bexToTaekangVO.getImg_file6().replace(tmpExt, nsiExt)));
        }
        if(bexToTaekangVO.getImg_url7() != null && bexToTaekangVO.getImg_url7().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url7(), extDataEncDir+bexToTaekangVO.getImg_file7());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file7());
            sendParam.add(new BasicNameValuePair("img_url7", imgUrl+bexToTaekangVO.getImg_file7().replace(tmpExt, nsiExt)));
        }
        if(bexToTaekangVO.getImg_url8() != null && bexToTaekangVO.getImg_url8().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url8(), extDataEncDir+bexToTaekangVO.getImg_file8());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file8());
            sendParam.add(new BasicNameValuePair("img_url8", imgUrl+bexToTaekangVO.getImg_file8().replace(tmpExt, nsiExt)));
        }
        if(bexToTaekangVO.getImg_url9() != null && bexToTaekangVO.getImg_url9().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url9(), extDataEncDir+bexToTaekangVO.getImg_file9());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file9());
            sendParam.add(new BasicNameValuePair("img_url9", imgUrl+bexToTaekangVO.getImg_file9().replace(tmpExt, nsiExt)));
        }
        if(bexToTaekangVO.getImg_url10() != null && bexToTaekangVO.getImg_url10().trim().length() != 0){
            commonUtil.copyFile(bexToTaekangVO.getImg_url10(), extDataEncDir+bexToTaekangVO.getImg_file10());
            tmpExt = "."+commonFileUpload.getFileExtension(bexToTaekangVO.getImg_file10());
            sendParam.add(new BasicNameValuePair("img_url10", imgUrl+bexToTaekangVO.getImg_file10().replace(tmpExt, nsiExt)));
        }
        sendParam.add(new BasicNameValuePair("bo_job", bexToTaekangVO.getBo_job()));
        sendParam.add(new BasicNameValuePair("bo_hp_com", bexToTaekangVO.getBo_hp_com()));
        sendParam.add(new BasicNameValuePair("bo_hp_kuk", bexToTaekangVO.getBo_hp_kuk()));
        sendParam.add(new BasicNameValuePair("bo_hp_bn", bexToTaekangVO.getBo_hp_bn()));
        sendParam.add(new BasicNameValuePair("bo_cust_id", bexToTaekangVO.getBo_cust_id()));
        sendParam.add(new BasicNameValuePair("bo_korn_nm", bexToTaekangVO.getBo_korn_nm()));
        sendParam.add(new BasicNameValuePair("agent1_level", bexToTaekangVO.getAgent1_level()));
        sendParam.add(new BasicNameValuePair("agent1_app_date", bexToTaekangVO.getAgent1_app_date()));
        sendParam.add(new BasicNameValuePair("agent1_name", bexToTaekangVO.getAgent1_name()));
        sendParam.add(new BasicNameValuePair("agent1_ssn", bexToTaekangVO.getAgent1_ssn()));
        sendParam.add(new BasicNameValuePair("agent1_ph11", bexToTaekangVO.getAgent1_ph11()));
        sendParam.add(new BasicNameValuePair("agent1_ph12", bexToTaekangVO.getAgent1_ph12()));
        sendParam.add(new BasicNameValuePair("agent1_ph13", bexToTaekangVO.getAgent1_ph13()));
        sendParam.add(new BasicNameValuePair("agent2_level", bexToTaekangVO.getAgent2_level()));
        sendParam.add(new BasicNameValuePair("agent2_app_date", bexToTaekangVO.getAgent2_app_date()));
        sendParam.add(new BasicNameValuePair("agent2_name", bexToTaekangVO.getAgent2_name()));
        sendParam.add(new BasicNameValuePair("agent2_ssn", bexToTaekangVO.getAgent2_ssn()));
        sendParam.add(new BasicNameValuePair("agent2_ph11", bexToTaekangVO.getAgent2_ph11()));
        sendParam.add(new BasicNameValuePair("agent2_ph12", bexToTaekangVO.getAgent2_ph12()));
        sendParam.add(new BasicNameValuePair("agent2_ph13", bexToTaekangVO.getAgent2_ph13()));
        sendParam.add(new BasicNameValuePair("agent3_level", bexToTaekangVO.getAgent3_level()));
        sendParam.add(new BasicNameValuePair("agent3_app_date", bexToTaekangVO.getAgent3_app_date()));
        sendParam.add(new BasicNameValuePair("agent3_name", bexToTaekangVO.getAgent3_name()));
        sendParam.add(new BasicNameValuePair("agent3_ssn", bexToTaekangVO.getAgent3_ssn()));
        sendParam.add(new BasicNameValuePair("agent3_ph11", bexToTaekangVO.getAgent3_ph11()));
        sendParam.add(new BasicNameValuePair("agent3_ph12", bexToTaekangVO.getAgent3_ph12()));
        sendParam.add(new BasicNameValuePair("agent3_ph13", bexToTaekangVO.getAgent3_ph13()));
        sendParam.add(new BasicNameValuePair("agent4_level", bexToTaekangVO.getAgent4_level()));
        sendParam.add(new BasicNameValuePair("agent4_app_date", bexToTaekangVO.getAgent4_app_date()));
        sendParam.add(new BasicNameValuePair("agent4_name", bexToTaekangVO.getAgent4_name()));
        sendParam.add(new BasicNameValuePair("agent4_ssn", bexToTaekangVO.getAgent4_ssn()));
        sendParam.add(new BasicNameValuePair("agent4_ph11", bexToTaekangVO.getAgent4_ph11()));
        sendParam.add(new BasicNameValuePair("agent4_ph12", bexToTaekangVO.getAgent4_ph12()));
        sendParam.add(new BasicNameValuePair("agent4_ph13", bexToTaekangVO.getAgent4_ph13()));
        sendParam.add(new BasicNameValuePair("agent5_level", bexToTaekangVO.getAgent5_level()));
        sendParam.add(new BasicNameValuePair("agent5_app_date", bexToTaekangVO.getAgent5_app_date()));
        sendParam.add(new BasicNameValuePair("agent5_name", bexToTaekangVO.getAgent5_name()));
        sendParam.add(new BasicNameValuePair("agent5_ssn", bexToTaekangVO.getAgent5_ssn()));
        sendParam.add(new BasicNameValuePair("agent5_ph11", bexToTaekangVO.getAgent5_ph11()));
        sendParam.add(new BasicNameValuePair("agent5_ph12", bexToTaekangVO.getAgent5_ph12()));
        sendParam.add(new BasicNameValuePair("agent5_ph13", bexToTaekangVO.getAgent5_ph13()));
        sendParam.add(new BasicNameValuePair("agent6_level", bexToTaekangVO.getAgent6_level()));
        sendParam.add(new BasicNameValuePair("agent6_app_date", bexToTaekangVO.getAgent6_app_date()));
        sendParam.add(new BasicNameValuePair("agent6_name", bexToTaekangVO.getAgent6_name()));
        sendParam.add(new BasicNameValuePair("agent6_ssn", bexToTaekangVO.getAgent6_ssn()));
        sendParam.add(new BasicNameValuePair("agent6_ph11", bexToTaekangVO.getAgent6_ph11()));
        sendParam.add(new BasicNameValuePair("agent6_ph12", bexToTaekangVO.getAgent6_ph12()));
        sendParam.add(new BasicNameValuePair("agent7_level", bexToTaekangVO.getAgent7_level()));
        sendParam.add(new BasicNameValuePair("agent7_app_date", bexToTaekangVO.getAgent7_app_date()));
        sendParam.add(new BasicNameValuePair("agent7_name", bexToTaekangVO.getAgent7_name()));
        sendParam.add(new BasicNameValuePair("agent7_ssn", bexToTaekangVO.getAgent7_ssn()));
        sendParam.add(new BasicNameValuePair("agent7_ph11", bexToTaekangVO.getAgent7_ph11()));
        sendParam.add(new BasicNameValuePair("agent7_ph12", bexToTaekangVO.getAgent7_ph12()));
        sendParam.add(new BasicNameValuePair("agent7_ph13", bexToTaekangVO.getAgent7_ph13()));
        sendParam.add(new BasicNameValuePair("agent8_level", bexToTaekangVO.getAgent8_level()));
        sendParam.add(new BasicNameValuePair("agent8_app_date", bexToTaekangVO.getAgent8_app_date()));
        sendParam.add(new BasicNameValuePair("agent8_name", bexToTaekangVO.getAgent8_name()));
        sendParam.add(new BasicNameValuePair("agent8_ssn", bexToTaekangVO.getAgent8_ssn()));
        sendParam.add(new BasicNameValuePair("agent8_ph11", bexToTaekangVO.getAgent8_ph11()));
        sendParam.add(new BasicNameValuePair("agent8_ph12", bexToTaekangVO.getAgent8_ph12()));
        sendParam.add(new BasicNameValuePair("agent8_ph13", bexToTaekangVO.getAgent8_ph13()));
        sendParam.add(new BasicNameValuePair("agent9_level", bexToTaekangVO.getAgent9_level()));
        sendParam.add(new BasicNameValuePair("agent9_app_date", bexToTaekangVO.getAgent9_app_date()));
        sendParam.add(new BasicNameValuePair("agent9_name", bexToTaekangVO.getAgent9_name()));
        sendParam.add(new BasicNameValuePair("agent9_ssn", bexToTaekangVO.getAgent9_ssn()));
        sendParam.add(new BasicNameValuePair("agent9_ph11", bexToTaekangVO.getAgent9_ph11()));
        sendParam.add(new BasicNameValuePair("agent9_ph12", bexToTaekangVO.getAgent9_ph12()));
        sendParam.add(new BasicNameValuePair("agent9_ph13", bexToTaekangVO.getAgent9_ph13()));
        /* 20150209 추가 BY 김성준 - 정보적법수집 */
        sendParam.add(new BasicNameValuePair("info_name", bexToTaekangVO.getInfo_name()));
        sendParam.add(new BasicNameValuePair("info_birth", bexToTaekangVO.getInfo_birth()));
        sendParam.add(new BasicNameValuePair("info_sex", bexToTaekangVO.getInfo_sex()));
        sendParam.add(new BasicNameValuePair("info_gubun", bexToTaekangVO.getInfo_gubun()));
        
        sendParam.add(new BasicNameValuePair("info_channel_1", bexToTaekangVO.getInfo_channel_1()));
        sendParam.add(new BasicNameValuePair("info_remark_1", bexToTaekangVO.getInfo_remark_1()));
        sendParam.add(new BasicNameValuePair("info_channel_2", bexToTaekangVO.getInfo_channel_2()));
        sendParam.add(new BasicNameValuePair("info_remark_2", bexToTaekangVO.getInfo_remark_2()));
        sendParam.add(new BasicNameValuePair("info_contact", bexToTaekangVO.getInfo_contact()));
        sendParam.add(new BasicNameValuePair("info_contact_remark", bexToTaekangVO.getInfo_contact_remark()));

        sendParam.add(new BasicNameValuePair("info_write_dt", bexToTaekangVO.getInfo_write_dt()));
        sendParam.add(new BasicNameValuePair("info_owner", bexToTaekangVO.getInfo_owner()));
        sendParam.add(new BasicNameValuePair("info_consulter", bexToTaekangVO.getInfo_consulter()));
        
/*     테스트 파라미터   
        sendParam.add(new BasicNameValuePair("pro_code", "001"));
        sendParam.add(new BasicNameValuePair("com_code", "starcredit"));
        sendParam.add(new BasicNameValuePair("cooperate_code", "t2012071301676"));
        sendParam.add(new BasicNameValuePair("inserted_home", "n"));
        sendParam.add(new BasicNameValuePair("click_no", "0"));
        sendParam.add(new BasicNameValuePair("var_flag", ""));
        sendParam.add(new BasicNameValuePair("app_type", "11"));
        sendParam.add(new BasicNameValuePair("name", "전산실테스트용"));
        sendParam.add(new BasicNameValuePair("ssn11", "722222"));
        sendParam.add(new BasicNameValuePair("ssn12", "2222222"));
        sendParam.add(new BasicNameValuePair("status", "b"));
        sendParam.add(new BasicNameValuePair("app_money", "1000"));
        sendParam.add(new BasicNameValuePair("confirm_money", "0"));
        sendParam.add(new BasicNameValuePair("out_money", "0"));
        sendParam.add(new BasicNameValuePair("pass_type", ""));
        sendParam.add(new BasicNameValuePair("bank_code", "01"));
        sendParam.add(new BasicNameValuePair("branch_code", "100"));
        sendParam.add(new BasicNameValuePair("manager_id", ""));
        sendParam.add(new BasicNameValuePair("confirm_manager1", ""));
        sendParam.add(new BasicNameValuePair("confirm_manager2", ""));
        sendParam.add(new BasicNameValuePair("out_manager", ""));
        sendParam.add(new BasicNameValuePair("a_time", "T20120714191402"));
        sendParam.add(new BasicNameValuePair("b_time", "0"));
        sendParam.add(new BasicNameValuePair("f_time", "0"));
        sendParam.add(new BasicNameValuePair("g_time", "0"));
        sendParam.add(new BasicNameValuePair("q_time", "0"));
        sendParam.add(new BasicNameValuePair("h_time", "0"));
        sendParam.add(new BasicNameValuePair("r_time", "0"));
        sendParam.add(new BasicNameValuePair("s_time", "0"));
        sendParam.add(new BasicNameValuePair("n_time", "0"));
        sendParam.add(new BasicNameValuePair("meet_date", "2013-08-01"));
        sendParam.add(new BasicNameValuePair("reject_type", ""));
        sendParam.add(new BasicNameValuePair("local", "99"));
        sendParam.add(new BasicNameValuePair("credit_check", ""));
        sendParam.add(new BasicNameValuePair("tel_check", ""));
        sendParam.add(new BasicNameValuePair("car_check", ""));
        sendParam.add(new BasicNameValuePair("doc_check", ""));
        sendParam.add(new BasicNameValuePair("absence_check", ""));
        sendParam.add(new BasicNameValuePair("delay_check", ""));
        sendParam.add(new BasicNameValuePair("bank_scan", "n"));
        sendParam.add(new BasicNameValuePair("update_date", "2013-08-01"));
        sendParam.add(new BasicNameValuePair("trade_cnt", "01"));
        sendParam.add(new BasicNameValuePair("bad_cnt", "0"));
        sendParam.add(new BasicNameValuePair("loan_date", "2013-08-01"));
        sendParam.add(new BasicNameValuePair("loan_cnt", "0"));
        sendParam.add(new BasicNameValuePair("delay_cnt", "0"));
        sendParam.add(new BasicNameValuePair("score_date", "2013-08-01"));
        sendParam.add(new BasicNameValuePair("last_score", ""));
        sendParam.add(new BasicNameValuePair("mem_info", ""));
        sendParam.add(new BasicNameValuePair("level", ""));
        sendParam.add(new BasicNameValuePair("plus_date", "2013-01-01"));
        sendParam.add(new BasicNameValuePair("badinfo_cnt", "0"));
        sendParam.add(new BasicNameValuePair("var1", "no data"));
        sendParam.add(new BasicNameValuePair("var2", "no data"));
        sendParam.add(new BasicNameValuePair("var3", "no data"));
        sendParam.add(new BasicNameValuePair("save_time", "no data"));
        sendParam.add(new BasicNameValuePair("save_status", "y"));
        sendParam.add(new BasicNameValuePair("l_time", ""));
        sendParam.add(new BasicNameValuePair("update_date2", ""));
        sendParam.add(new BasicNameValuePair("score_date2", ""));
        sendParam.add(new BasicNameValuePair("result_check_1", ""));
        sendParam.add(new BasicNameValuePair("result_check_2", ""));
        sendParam.add(new BasicNameValuePair("reject_type_b", ""));
        sendParam.add(new BasicNameValuePair("reloan_check", ""));
        sendParam.add(new BasicNameValuePair("sub_com_code", "프라임"));
        sendParam.add(new BasicNameValuePair("sub_com_code2", "no data"));
        sendParam.add(new BasicNameValuePair("inserted_flag", "y"));
        sendParam.add(new BasicNameValuePair("ch_date", "20120713191403"));
        sendParam.add(new BasicNameValuePair("ch_flag", "y"));
        sendParam.add(new BasicNameValuePair("guarantor", "y"));
        sendParam.add(new BasicNameValuePair("surety", "N"));
        sendParam.add(new BasicNameValuePair("b_new_addr_yn", "Y"));
        sendParam.add(new BasicNameValuePair("h_new_addr_yn", "Y"));
        sendParam.add(new BasicNameValuePair("o_new_addr_yn", "Y"));
        sendParam.add(new BasicNameValuePair("img_url1", "http://61.250.227.242/file/1.jpg"));
        sendParam.add(new BasicNameValuePair("img_url2", ""));
        sendParam.add(new BasicNameValuePair("img_url3", ""));
        sendParam.add(new BasicNameValuePair("img_url4", ""));
        sendParam.add(new BasicNameValuePair("img_url5", ""));
        sendParam.add(new BasicNameValuePair("img_url6", ""));
        sendParam.add(new BasicNameValuePair("img_url7", ""));
        sendParam.add(new BasicNameValuePair("img_url8", ""));
        sendParam.add(new BasicNameValuePair("img_url9", ""));
        sendParam.add(new BasicNameValuePair("img_url10", ""));
        sendParam.add(new BasicNameValuePair("img_type1", "F"));
        sendParam.add(new BasicNameValuePair("img_type2", "F"));
        sendParam.add(new BasicNameValuePair("img_type3", "F"));
        sendParam.add(new BasicNameValuePair("img_type4", "F"));
        sendParam.add(new BasicNameValuePair("img_type5", "F"));
        sendParam.add(new BasicNameValuePair("img_type6", "F"));
        sendParam.add(new BasicNameValuePair("img_type7", "F"));
        sendParam.add(new BasicNameValuePair("img_type8", "F"));
        sendParam.add(new BasicNameValuePair("img_type9", "F"));
        sendParam.add(new BasicNameValuePair("img_type10", "F"));
        sendParam.add(new BasicNameValuePair("agent1_level", "1"));
        sendParam.add(new BasicNameValuePair("agent1_app_date", "2009-10-30"));
        sendParam.add(new BasicNameValuePair("agent1_name", "에이스"));
        sendParam.add(new BasicNameValuePair("agent1_ssn", "000000"));
        sendParam.add(new BasicNameValuePair("agent1_ph11", "032"));
        sendParam.add(new BasicNameValuePair("agent1_ph12", "328"));
        sendParam.add(new BasicNameValuePair("agent1_ph13", "3994"));
        sendParam.add(new BasicNameValuePair("agent2_level", "2"));
        sendParam.add(new BasicNameValuePair("agent2_app_date", "2009-10-30"));
        sendParam.add(new BasicNameValuePair("agent2_name", "도움론(대부중개)"));
        sendParam.add(new BasicNameValuePair("agent2_ssn", "2012-경기부천"));
        sendParam.add(new BasicNameValuePair("agent2_ph11", "02"));
        sendParam.add(new BasicNameValuePair("agent2_ph12", "2604"));
        sendParam.add(new BasicNameValuePair("agent2_ph13", "9295"));
        sendParam.add(new BasicNameValuePair("agent3_level", "3"));
        sendParam.add(new BasicNameValuePair("agent3_app_date", "2014-02-11"));
        sendParam.add(new BasicNameValuePair("agent3_name", "(주)티엠피플대부중개"));
        sendParam.add(new BasicNameValuePair("agent3_ssn", "2013-서울관악-00056"));
        sendParam.add(new BasicNameValuePair("agent3_ph11", "02"));
        sendParam.add(new BasicNameValuePair("agent3_ph12", "888"));
        sendParam.add(new BasicNameValuePair("agent3_ph13", "7477"));
        sendParam.add(new BasicNameValuePair("info_name", "테스트"));
        sendParam.add(new BasicNameValuePair("info_birth", "19810919"));
        sendParam.add(new BasicNameValuePair("info_sex", "M"));
        sendParam.add(new BasicNameValuePair("info_channel_1", "40304"));
        sendParam.add(new BasicNameValuePair("info_remark_1", "WWW.SWISS-LOAN.NET"));
        sendParam.add(new BasicNameValuePair("info_channel_2", "40503"));
        sendParam.add(new BasicNameValuePair("info_remark_2", "agde"));
        sendParam.add(new BasicNameValuePair("info_contact", "40499"));
        sendParam.add(new BasicNameValuePair("info_contact_remark", ""));
        sendParam.add(new BasicNameValuePair("info_write_dt", "20140616"));
        sendParam.add(new BasicNameValuePair("info_owner", "곽순주"));
        sendParam.add(new BasicNameValuePair("info_consulter", "김현정"));
        sendParam.add(new BasicNameValuePair("info_gubun", "40602"));
        sendParam.add(new BasicNameValuePair("img_exe1", "jpg"));
        sendParam.add(new BasicNameValuePair("img_exe2", "jpg"));
        sendParam.add(new BasicNameValuePair("img_exe3", "jpg"));
        sendParam.add(new BasicNameValuePair("img_exe4", "jpg"));
        sendParam.add(new BasicNameValuePair("img_exe5", "jpg"));
        sendParam.add(new BasicNameValuePair("img_exe6", "jpg"));
        sendParam.add(new BasicNameValuePair("img_exe7", "jpg"));
        sendParam.add(new BasicNameValuePair("img_exe8", "jpg"));
        sendParam.add(new BasicNameValuePair("img_exe9", "jpg"));
        sendParam.add(new BasicNameValuePair("img_exe10", "jpg"));
        sendParam.add(new BasicNameValuePair("loan_and_card_list_no", "1299059"));
        sendParam.add(new BasicNameValuePair("ph11", "02"));
        sendParam.add(new BasicNameValuePair("ph12", "1122"));
        sendParam.add(new BasicNameValuePair("ph13", "0011"));
        sendParam.add(new BasicNameValuePair("ph1_name", ""));
        sendParam.add(new BasicNameValuePair("ph1_name_rel", "1"));
        sendParam.add(new BasicNameValuePair("ph21", "010"));
        sendParam.add(new BasicNameValuePair("ph22", "1234"));
        sendParam.add(new BasicNameValuePair("ph23", "5678"));
        sendParam.add(new BasicNameValuePair("ph2_name", ""));
        sendParam.add(new BasicNameValuePair("ph2_name_rel", "1"));
        sendParam.add(new BasicNameValuePair("h_zip11", "123"));
        sendParam.add(new BasicNameValuePair("h_zip12", "456"));
        sendParam.add(new BasicNameValuePair("h_addr11", "서울 마포구 양화로10길 55-3"));
        sendParam.add(new BasicNameValuePair("h_addr12", "한송빌라 204(새주소)"));
        sendParam.add(new BasicNameValuePair("h_zip21", "789"));
        sendParam.add(new BasicNameValuePair("h_zip22", "987"));
        sendParam.add(new BasicNameValuePair("h_addr21", "서울 송파구 도곡로64길 13"));
        sendParam.add(new BasicNameValuePair("h_addr22", "104-2호(새주소)"));
        sendParam.add(new BasicNameValuePair("h_stat", ""));
        sendParam.add(new BasicNameValuePair("h_size", "10"));
        sendParam.add(new BasicNameValuePair("h_price", "20"));
        sendParam.add(new BasicNameValuePair("h_size1", "50"));
        sendParam.add(new BasicNameValuePair("h_size2", "100"));
        sendParam.add(new BasicNameValuePair("h_size3", "150"));
        sendParam.add(new BasicNameValuePair("h_price1", "11"));
        sendParam.add(new BasicNameValuePair("h_price2", "23"));
        sendParam.add(new BasicNameValuePair("h_price3", "33"));
        sendParam.add(new BasicNameValuePair("h_name1", ""));
        sendParam.add(new BasicNameValuePair("h_name2", ""));
        sendParam.add(new BasicNameValuePair("h_name3", ""));
        sendParam.add(new BasicNameValuePair("h_rel1", ""));
        sendParam.add(new BasicNameValuePair("h_rel2", ""));
        sendParam.add(new BasicNameValuePair("h_rel3", ""));
        sendParam.add(new BasicNameValuePair("h_name", ""));
        sendParam.add(new BasicNameValuePair("h_rel", ""));
        sendParam.add(new BasicNameValuePair("h_date1", "0"));
        sendParam.add(new BasicNameValuePair("h_date2", "0"));
        sendParam.add(new BasicNameValuePair("h_clothing", ""));
        sendParam.add(new BasicNameValuePair("h_fam1", ""));
        sendParam.add(new BasicNameValuePair("h_fam2", ""));
        sendParam.add(new BasicNameValuePair("h_fam3", ""));
        sendParam.add(new BasicNameValuePair("h_fam4", ""));
        sendParam.add(new BasicNameValuePair("h_fam5", ""));
        sendParam.add(new BasicNameValuePair("h_fam6", ""));
        sendParam.add(new BasicNameValuePair("h_fam7", ""));
        sendParam.add(new BasicNameValuePair("h_fam8", ""));
        sendParam.add(new BasicNameValuePair("h_fam9", ""));
        sendParam.add(new BasicNameValuePair("marry", "y"));
        sendParam.add(new BasicNameValuePair("job", "A"));
        sendParam.add(new BasicNameValuePair("agree_chk", ""));
        sendParam.add(new BasicNameValuePair("email", "@"));
        sendParam.add(new BasicNameValuePair("c_name", ""));
        sendParam.add(new BasicNameValuePair("c_rel", ""));
        sendParam.add(new BasicNameValuePair("c_ssn1", ""));
        sendParam.add(new BasicNameValuePair("c_ssn2", ""));
        sendParam.add(new BasicNameValuePair("c_age", ""));
        sendParam.add(new BasicNameValuePair("c_mobile1", ""));
        sendParam.add(new BasicNameValuePair("c_mobile2", ""));
        sendParam.add(new BasicNameValuePair("c_mobile3", ""));
        sendParam.add(new BasicNameValuePair("c_email", ""));
        sendParam.add(new BasicNameValuePair("s_jobtype", "0"));
        sendParam.add(new BasicNameValuePair("s_com", "뉴몬온먼데이"));
        sendParam.add(new BasicNameValuePair("s_tel1", "070"));
        sendParam.add(new BasicNameValuePair("s_tel2", "4157"));
        sendParam.add(new BasicNameValuePair("s_tel3", "1364"));
        sendParam.add(new BasicNameValuePair("s_fax1", ""));
        sendParam.add(new BasicNameValuePair("s_fax2", ""));
        sendParam.add(new BasicNameValuePair("s_fax3", ""));
        sendParam.add(new BasicNameValuePair("s_homepg", ""));
        sendParam.add(new BasicNameValuePair("s_famnum", "0"));
        sendParam.add(new BasicNameValuePair("s_date1", "2011"));
        sendParam.add(new BasicNameValuePair("s_date2", "7"));
        sendParam.add(new BasicNameValuePair("s_class", "1"));
        sendParam.add(new BasicNameValuePair("s_time1", "0"));
        sendParam.add(new BasicNameValuePair("s_time2", "0"));
        sendParam.add(new BasicNameValuePair("s_phone1", ""));
        sendParam.add(new BasicNameValuePair("s_phone2", ""));
        sendParam.add(new BasicNameValuePair("s_phone3", ""));
        sendParam.add(new BasicNameValuePair("s_zip1", "771"));
        sendParam.add(new BasicNameValuePair("s_zip2", "323"));
        sendParam.add(new BasicNameValuePair("s_addr1", "서울 종로구 새문안로5길 37(도렴동,도렴빌딩)"));
        sendParam.add(new BasicNameValuePair("s_addr2", "11층(새주소)"));
        sendParam.add(new BasicNameValuePair("s_money", "0"));
        sendParam.add(new BasicNameValuePair("s_day", "10"));
        sendParam.add(new BasicNameValuePair("s_bonus1", ""));
        sendParam.add(new BasicNameValuePair("s_bonus2", "0"));
        sendParam.add(new BasicNameValuePair("s_yincome", "5000"));
        sendParam.add(new BasicNameValuePair("s_incometype", ""));
        sendParam.add(new BasicNameValuePair("s_jobpart", "기타부서"));
        sendParam.add(new BasicNameValuePair("s_hiredtype", ""));
        sendParam.add(new BasicNameValuePair("c_jobtype", "0"));
        sendParam.add(new BasicNameValuePair("c_com", ""));
        sendParam.add(new BasicNameValuePair("c_regtype", ""));
        sendParam.add(new BasicNameValuePair("c_regdate1", ""));
        sendParam.add(new BasicNameValuePair("c_regdate2", "0"));
        sendParam.add(new BasicNameValuePair("c_regdate3", "0"));
        sendParam.add(new BasicNameValuePair("c_ssn", ""));
        sendParam.add(new BasicNameValuePair("c_ingdate1", "0"));
        sendParam.add(new BasicNameValuePair("c_ingdate2", "0"));
        sendParam.add(new BasicNameValuePair("c_money", "0"));
        sendParam.add(new BasicNameValuePair("c_zip1", "120"));
        sendParam.add(new BasicNameValuePair("c_zip2", "805"));
        sendParam.add(new BasicNameValuePair("c_addr1", "서울특별시 서대문구"));
        sendParam.add(new BasicNameValuePair("c_addr2", "186-229"));
        sendParam.add(new BasicNameValuePair("c_phone1", "02"));
        sendParam.add(new BasicNameValuePair("c_phone2", "3417"));
        sendParam.add(new BasicNameValuePair("c_phone3", "1244"));
        sendParam.add(new BasicNameValuePair("c_fax1", "02"));
        sendParam.add(new BasicNameValuePair("c_fax2", "3411"));
        sendParam.add(new BasicNameValuePair("c_fax3", "7815"));
        sendParam.add(new BasicNameValuePair("c_exch", ""));
        sendParam.add(new BasicNameValuePair("c_exname", ""));
        sendParam.add(new BasicNameValuePair("c_exph1", ""));
        sendParam.add(new BasicNameValuePair("c_exph2", ""));
        sendParam.add(new BasicNameValuePair("c_exph3", ""));
        sendParam.add(new BasicNameValuePair("c_worker", "0"));
        sendParam.add(new BasicNameValuePair("b_jobtype", "0"));
        sendParam.add(new BasicNameValuePair("b_com", ""));
        sendParam.add(new BasicNameValuePair("b_tel1", "02"));
        sendParam.add(new BasicNameValuePair("b_tel2", "1234"));
        sendParam.add(new BasicNameValuePair("b_tel3", "5678"));
        sendParam.add(new BasicNameValuePair("b_fax1", ""));
        sendParam.add(new BasicNameValuePair("b_fax2", ""));
        sendParam.add(new BasicNameValuePair("b_fax3", ""));
        sendParam.add(new BasicNameValuePair("b_homepg", ""));
        sendParam.add(new BasicNameValuePair("b_usernum", "0"));
        sendParam.add(new BasicNameValuePair("b_date1", "0"));
        sendParam.add(new BasicNameValuePair("b_date2", "0"));
        sendParam.add(new BasicNameValuePair("b_class", ""));
        sendParam.add(new BasicNameValuePair("b_time1", "0"));
        sendParam.add(new BasicNameValuePair("b_time2", "0"));
        sendParam.add(new BasicNameValuePair("b_phone1", "031"));
        sendParam.add(new BasicNameValuePair("b_phone2", "979"));
        sendParam.add(new BasicNameValuePair("b_phone3", "4111"));
        sendParam.add(new BasicNameValuePair("b_zip1", ""));
        sendParam.add(new BasicNameValuePair("b_zip2", ""));
        sendParam.add(new BasicNameValuePair("b_addr1", ""));
        sendParam.add(new BasicNameValuePair("b_addr2", ""));
        sendParam.add(new BasicNameValuePair("b_money", ""));
        sendParam.add(new BasicNameValuePair("b_day", "0"));
        sendParam.add(new BasicNameValuePair("b_bonus1", ""));
        sendParam.add(new BasicNameValuePair("b_bonus2", "0"));
        sendParam.add(new BasicNameValuePair("b_income", "0"));
        sendParam.add(new BasicNameValuePair("b_incometype", ""));
        sendParam.add(new BasicNameValuePair("b_hiredtype", ""));
        sendParam.add(new BasicNameValuePair("b_job", ""));
        sendParam.add(new BasicNameValuePair("g_grade", ""));
        sendParam.add(new BasicNameValuePair("g_part", ""));
        sendParam.add(new BasicNameValuePair("g_year", "0"));
        sendParam.add(new BasicNameValuePair("g_month", "0"));
        sendParam.add(new BasicNameValuePair("g_class", ""));
        sendParam.add(new BasicNameValuePair("g_time1", "0"));
        sendParam.add(new BasicNameValuePair("g_time2", "0"));
        sendParam.add(new BasicNameValuePair("g_com", ""));
        sendParam.add(new BasicNameValuePair("g_phone1", ""));
        sendParam.add(new BasicNameValuePair("g_phone2", ""));
        sendParam.add(new BasicNameValuePair("g_phone3", ""));
        sendParam.add(new BasicNameValuePair("g_money", "0"));
        sendParam.add(new BasicNameValuePair("g_day", "0"));
        sendParam.add(new BasicNameValuePair("g_ymoney", "0"));
        sendParam.add(new BasicNameValuePair("g_zip1", ""));
        sendParam.add(new BasicNameValuePair("g_zip2", ""));
        sendParam.add(new BasicNameValuePair("g_addr1", ""));
        sendParam.add(new BasicNameValuePair("g_addr2", ""));
        sendParam.add(new BasicNameValuePair("p_year", "0"));
        sendParam.add(new BasicNameValuePair("p_month", "0"));
        sendParam.add(new BasicNameValuePair("p_hiredtype", ""));
        sendParam.add(new BasicNameValuePair("p_class", ""));
        sendParam.add(new BasicNameValuePair("p_time1", "0"));
        sendParam.add(new BasicNameValuePair("p_time2", "0"));
        sendParam.add(new BasicNameValuePair("p_com", ""));
        sendParam.add(new BasicNameValuePair("p_phone1", "031"));
        sendParam.add(new BasicNameValuePair("p_phone2", "979"));
        sendParam.add(new BasicNameValuePair("p_phone3", "1477"));
        sendParam.add(new BasicNameValuePair("p_money", "0"));
        sendParam.add(new BasicNameValuePair("p_day", "0"));
        sendParam.add(new BasicNameValuePair("p_ymoney", "0"));
        sendParam.add(new BasicNameValuePair("p_zip1", "412"));
        sendParam.add(new BasicNameValuePair("p_zip2", "221"));
        sendParam.add(new BasicNameValuePair("p_addr1", "경기도 고양시 덕양구 행신로143번길 14-4(행신동)"));
        sendParam.add(new BasicNameValuePair("p_addr2", "샘터APT 101-111"));
        sendParam.add(new BasicNameValuePair("p_incometype", ""));
        sendParam.add(new BasicNameValuePair("p_jobpart", ""));
        sendParam.add(new BasicNameValuePair("p_phone21", "031"));
        sendParam.add(new BasicNameValuePair("p_phone22", "999"));
        sendParam.add(new BasicNameValuePair("p_phone23", "7141"));
        sendParam.add(new BasicNameValuePair("p_homepg", ""));
        sendParam.add(new BasicNameValuePair("p_jobtype", "0"));
        sendParam.add(new BasicNameValuePair("p_worker", "0"));
        sendParam.add(new BasicNameValuePair("p_bonus1", ""));
        sendParam.add(new BasicNameValuePair("p_bonus2", "0"));
        sendParam.add(new BasicNameValuePair("m_day", "0"));
        sendParam.add(new BasicNameValuePair("m_time1", "0"));
        sendParam.add(new BasicNameValuePair("m_time2", "0"));
        sendParam.add(new BasicNameValuePair("m_use", "2"));
        sendParam.add(new BasicNameValuePair("m_bcom", "0"));
        sendParam.add(new BasicNameValuePair("m_bssn", ""));
        sendParam.add(new BasicNameValuePair("m_bname", ""));
        sendParam.add(new BasicNameValuePair("a_com1", ""));
        sendParam.add(new BasicNameValuePair("a_money1", ""));
        sendParam.add(new BasicNameValuePair("a_exch1", "0"));
        sendParam.add(new BasicNameValuePair("a_com2", ""));
        sendParam.add(new BasicNameValuePair("a_money2", "0"));
        sendParam.add(new BasicNameValuePair("a_exch2", "0"));
        sendParam.add(new BasicNameValuePair("a_com3", ""));
        sendParam.add(new BasicNameValuePair("a_money3", "0"));
        sendParam.add(new BasicNameValuePair("a_exch3", "0"));
        sendParam.add(new BasicNameValuePair("a_com4", ""));
        sendParam.add(new BasicNameValuePair("a_money4", "0"));
        sendParam.add(new BasicNameValuePair("a_exch4", "0"));
        sendParam.add(new BasicNameValuePair("a_com5", ""));
        sendParam.add(new BasicNameValuePair("a_money5", "0"));
        sendParam.add(new BasicNameValuePair("a_exch5", "0"));
        sendParam.add(new BasicNameValuePair("a_com6", ""));
        sendParam.add(new BasicNameValuePair("a_money6", "0"));
        sendParam.add(new BasicNameValuePair("a_exch6", "0"));
        sendParam.add(new BasicNameValuePair("ip_addr", "211.124.142.33"));
        sendParam.add(new BasicNameValuePair("secret", "n"));
        sendParam.add(new BasicNameValuePair("for_seanch_account_authkeyno", ""));
        sendParam.add(new BasicNameValuePair("for_seanch_account_anumber", ""));
        sendParam.add(new BasicNameValuePair("for_seanch_account_userid", ""));
        sendParam.add(new BasicNameValuePair("scholar", "0"));
        sendParam.add(new BasicNameValuePair("car_own", ""));
        sendParam.add(new BasicNameValuePair("app_path", ""));
        sendParam.add(new BasicNameValuePair("communication_s_time", "0"));
        sendParam.add(new BasicNameValuePair("communication_e_time", "0"));
        sendParam.add(new BasicNameValuePair("use_cat_no", ""));
        sendParam.add(new BasicNameValuePair("bank_return_money", "0"));
        sendParam.add(new BasicNameValuePair("bank_cat_no", "26"));
        sendParam.add(new BasicNameValuePair("bank_loan_count", "0"));
        sendParam.add(new BasicNameValuePair("bank_loan_money", "0"));
        sendParam.add(new BasicNameValuePair("bank_ssn", "030301000978"));
        sendParam.add(new BasicNameValuePair("interest_return_hope_day", "0"));
        sendParam.add(new BasicNameValuePair("car_name", ""));
        sendParam.add(new BasicNameValuePair("car_name_rel", ""));
        sendParam.add(new BasicNameValuePair("car_ssn11", ""));
        sendParam.add(new BasicNameValuePair("car_ssn12", ""));
        sendParam.add(new BasicNameValuePair("car_maker", ""));
        sendParam.add(new BasicNameValuePair("car_no", ""));
        sendParam.add(new BasicNameValuePair("sc_com", ""));
        sendParam.add(new BasicNameValuePair("sc_number", ""));
        sendParam.add(new BasicNameValuePair("sc_grade_cat_no", "0"));
        sendParam.add(new BasicNameValuePair("sc_status_cat_no", "0"));
        sendParam.add(new BasicNameValuePair("sc_in_year", ""));
        sendParam.add(new BasicNameValuePair("sc_zip1", ""));
        sendParam.add(new BasicNameValuePair("sc_zip2", ""));
        sendParam.add(new BasicNameValuePair("sc_addr1", ""));
        sendParam.add(new BasicNameValuePair("sc_addr2", ""));
        sendParam.add(new BasicNameValuePair("sc_army", ""));
        sendParam.add(new BasicNameValuePair("sc_phone1", ""));
        sendParam.add(new BasicNameValuePair("sc_phone2", ""));
        sendParam.add(new BasicNameValuePair("sc_phone3", ""));
        sendParam.add(new BasicNameValuePair("sc_alba_chk", ""));
        sendParam.add(new BasicNameValuePair("sc_alba_name", ""));
        sendParam.add(new BasicNameValuePair("sc_alba_phone1", ""));
        sendParam.add(new BasicNameValuePair("sc_alba_phone2", ""));
        sendParam.add(new BasicNameValuePair("sc_alba_phone3", ""));
        sendParam.add(new BasicNameValuePair("sc_alba_time1", "0"));
        sendParam.add(new BasicNameValuePair("sc_alba_time2", "0"));
        sendParam.add(new BasicNameValuePair("h_type_tmp", ""));
        sendParam.add(new BasicNameValuePair("h_type", "3"));
        sendParam.add(new BasicNameValuePair("b_homepage", ""));
        sendParam.add(new BasicNameValuePair("c_homepage", ""));
        sendParam.add(new BasicNameValuePair("confirm_memo", ""));
        sendParam.add(new BasicNameValuePair("sh_zip11", "150010"));
        sendParam.add(new BasicNameValuePair("sh_addr11", "서울특별시 영등포구 은행로 55(여의도동)"));
        sendParam.add(new BasicNameValuePair("sh_addr12", "우림 아파트 1203-202(새주소)"));
        sendParam.add(new BasicNameValuePair("sh_zip21", "121020"));
        sendParam.add(new BasicNameValuePair("sh_addr21", "서울특별시 마포구 만리재로 32(신공덕동)"));
        sendParam.add(new BasicNameValuePair("sh_addr22", "성림빌라 11-10(새주소)"));
        sendParam.add(new BasicNameValuePair("memo", ""));
        sendParam.add(new BasicNameValuePair("loan_and_card_list_no", "1299059"));
        sendParam.add(new BasicNameValuePair("bo_cust_id", "901211*******"));
        sendParam.add(new BasicNameValuePair("bo_korn_nm", "테스트"));
        sendParam.add(new BasicNameValuePair("bo_bank_cd", "32007"));
        sendParam.add(new BasicNameValuePair("bo_bank_acnt_no", "0303020781789"));
        sendParam.add(new BasicNameValuePair("bo_ref_bank_cd2", "32001"));
        sendParam.add(new BasicNameValuePair("bo_ref_bank_acnt_no2", "78781879996"));
        sendParam.add(new BasicNameValuePair("bo_offc_nm", "태강"));
        sendParam.add(new BasicNameValuePair("bo_dept", "영업팀"));
        sendParam.add(new BasicNameValuePair("bo_office_nm3", "bck_it"));
        sendParam.add(new BasicNameValuePair("bo_role", "12906"));
        sendParam.add(new BasicNameValuePair("bo_job_divi", "13901"));
        sendParam.add(new BasicNameValuePair("bo_job", "10102"));
        sendParam.add(new BasicNameValuePair("bo_stat_cnt", "13603"));
        sendParam.add(new BasicNameValuePair("bo_com_term", "63302"));
        sendParam.add(new BasicNameValuePair("bo_role_memo", "대리"));
        sendParam.add(new BasicNameValuePair("bo_job2", "20102"));
        sendParam.add(new BasicNameValuePair("bo_job2_sub", "20302"));
        sendParam.add(new BasicNameValuePair("bo_sa_no", "12-148971"));
        sendParam.add(new BasicNameValuePair("bo_rsdn_ty", "10300"));
        sendParam.add(new BasicNameValuePair("bo_home_onr", "소유자명"));
        sendParam.add(new BasicNameValuePair("bo_guar_amt", "5000"));
        sendParam.add(new BasicNameValuePair("bo_monthly_rent", "0"));
        sendParam.add(new BasicNameValuePair("bo_rsdn_fm", "10202"));
        sendParam.add(new BasicNameValuePair("bo_home_yymm", "201204"));
        sendParam.add(new BasicNameValuePair("bo_life_term", "63401"));
        sendParam.add(new BasicNameValuePair("bo_home_onr_rel_ty", "10407"));
        sendParam.add(new BasicNameValuePair("bo_sons", "1"));
        sendParam.add(new BasicNameValuePair("bo_sons_memo", "부양가족수"));
        sendParam.add(new BasicNameValuePair("bo_toget_rem", "2"));
        sendParam.add(new BasicNameValuePair("bo_spouse_amt_yn", "63603"));
        sendParam.add(new BasicNameValuePair("bo_spouse_amt", "9000"));
        sendParam.add(new BasicNameValuePair("bo_life_ty", "2"));
        sendParam.add(new BasicNameValuePair("bo_incom_divi", "14001"));
        sendParam.add(new BasicNameValuePair("bo_slry_ty", "35101"));
        sendParam.add(new BasicNameValuePair("bo_slry_ty_memo", ""));
        sendParam.add(new BasicNameValuePair("bo_slry_dd", "52131"));
        sendParam.add(new BasicNameValuePair("bo_sim2", "18"));
        sendParam.add(new BasicNameValuePair("bo_land", "1"));
        sendParam.add(new BasicNameValuePair("bo_land_memo", "기타부동산"));
        sendParam.add(new BasicNameValuePair("bo_sise_amt", "10000"));
        sendParam.add(new BasicNameValuePair("bo_m2", "10"));
        sendParam.add(new BasicNameValuePair("bo_loan_cnt", "5"));
        sendParam.add(new BasicNameValuePair("bo_other_loan", "5000"));
        sendParam.add(new BasicNameValuePair("bo_bank_cheamu", "1"));
        sendParam.add(new BasicNameValuePair("bo_cheamu_money", "1000"));
        sendParam.add(new BasicNameValuePair("bo_bank_dambo", "2"));
        sendParam.add(new BasicNameValuePair("bo_bank_dambo_money", "2000"));
        sendParam.add(new BasicNameValuePair("bo_bank_dambo_m", "200"));
        sendParam.add(new BasicNameValuePair("bo_cash_count", "3"));
        sendParam.add(new BasicNameValuePair("bo_cash_money", "3000"));
        sendParam.add(new BasicNameValuePair("bo_count", "4"));
        sendParam.add(new BasicNameValuePair("bo_money", "4000"));
        sendParam.add(new BasicNameValuePair("bo_bad_memo", "채무현황"));
        sendParam.add(new BasicNameValuePair("bo_army_ty", "3"));
        sendParam.add(new BasicNameValuePair("bo_army_memo", "병역면제"));
        sendParam.add(new BasicNameValuePair("bo_e_mail", "ddwtwe@chollian.net"));
        sendParam.add(new BasicNameValuePair("bo_wed_ty", "12402"));
        sendParam.add(new BasicNameValuePair("bo_remk", "공지사항"));
        sendParam.add(new BasicNameValuePair("bo_insure_ty", "2"));
        sendParam.add(new BasicNameValuePair("bo_mm_slry", "500"));
        sendParam.add(new BasicNameValuePair("bo_yy_incm", "6000"));
        sendParam.add(new BasicNameValuePair("bo_bonus", "2000"));
        sendParam.add(new BasicNameValuePair("bo_cheamu_money_m", "500"));
        sendParam.add(new BasicNameValuePair("bo_other_loan_m", "300"));
        sendParam.add(new BasicNameValuePair("bo_hom_post_no", "120711"));
        sendParam.add(new BasicNameValuePair("bo_hom_post_addr", "서울특별시 서대문구 통일로 413  (홍제동)"));
        sendParam.add(new BasicNameValuePair("bo_hom_stno", "(새주소)1-7"));
        sendParam.add(new BasicNameValuePair("bo_hom_tel_zone", "02"));
        sendParam.add(new BasicNameValuePair("bo_hom_tel_kuk", "3123"));
        sendParam.add(new BasicNameValuePair("bo_hom_tel_bn", "1578"));
        sendParam.add(new BasicNameValuePair("bo_hom_phone_own", "현거주지명의인"));
        sendParam.add(new BasicNameValuePair("bo_hom_phone_rel_ty", "10422"));
        sendParam.add(new BasicNameValuePair("bo_hom_addr_memo", "현거주지메모"));
        sendParam.add(new BasicNameValuePair("bo_bir_post_no", "412220"));
        sendParam.add(new BasicNameValuePair("bo_bir_post_addr", "경기도 고양시 덕양구 무원행신동, 행신동센스빌1차)"));
        sendParam.add(new BasicNameValuePair("bo_bir_stno", "423-11 행신빌라 304호(새주소)"));
        sendParam.add(new BasicNameValuePair("bo_bir_tel_zone", "031"));
        sendParam.add(new BasicNameValuePair("bo_bir_tel_kuk", "979"));
        sendParam.add(new BasicNameValuePair("bo_bir_tel_bn", "4177"));
        sendParam.add(new BasicNameValuePair("bo_bir_phone_own", "자택주소명의인"));
        sendParam.add(new BasicNameValuePair("bo_bir_phone_rel_ty", "10407"));
        sendParam.add(new BasicNameValuePair("bo_bir_addr_memo", "자택주소메모"));
        sendParam.add(new BasicNameValuePair("bo_off_post_no", "110730"));
        sendParam.add(new BasicNameValuePair("bo_off_post_addr", "서울특별시 종로구 새문안로 58  (신문로2가)"));
        sendParam.add(new BasicNameValuePair("bo_off_stno", "도렴빌딩27-1(새주소)"));
        sendParam.add(new BasicNameValuePair("bo_off_tel_zone", "02"));
        sendParam.add(new BasicNameValuePair("bo_off_tel_kuk", "789"));
        sendParam.add(new BasicNameValuePair("bo_off_tel_bn", "1053"));
        sendParam.add(new BasicNameValuePair("bo_off_addr_memo", "직장메모"));
        sendParam.add(new BasicNameValuePair("bo_off_inner_num", "053"));
        sendParam.add(new BasicNameValuePair("bo_off_dir_tel_zone", "02"));
        sendParam.add(new BasicNameValuePair("bo_off_dir_tel_kuk", "789"));
        sendParam.add(new BasicNameValuePair("bo_off_dir_tel_bn", "1214"));
        sendParam.add(new BasicNameValuePair("bo_hp_com", "010"));
        sendParam.add(new BasicNameValuePair("bo_email", "010"));
        sendParam.add(new BasicNameValuePair("bo_hp_kuk", "4763"));
        sendParam.add(new BasicNameValuePair("bo_hp_bn", "1234"));
        sendParam.add(new BasicNameValuePair("bo_hp_rel_ty", "10422"));
        sendParam.add(new BasicNameValuePair("bo_hp_own", "본인"));
        sendParam.add(new BasicNameValuePair("bo_hp_com_info", "25001"));
        sendParam.add(new BasicNameValuePair("bo_hp_memo", "핸드폰메모"));
        sendParam.add(new BasicNameValuePair("bo_crt_man", "00000"));
        sendParam.add(new BasicNameValuePair("bo_crt_dt", "20120714"));
        sendParam.add(new BasicNameValuePair("bo_crt_tm", "184834"));
        sendParam.add(new BasicNameValuePair("bo_surety_rel_ty", "10404"));
        */
        
        logger.debug("requestHttpPost parameter");
        for(NameValuePair dummy: sendParam){
            logger.debug(dummy.getName()+":["+dummy.getValue()+"]");
        }
        CommonHttpClient commonHttpClient = new CommonHttpClient();
        logger.debug("Call BexToTaekangService requestHttpPost");
        resultPost = commonHttpClient.requestHttpPost(bexToTaekangVO.getDs_url(),sendParam,"euc-kr");
        //resultPost = commonHttpClient.requestHttpPost("http://agency.taegang.co.kr/Agent/AgentOk.aspx",sendParam,"euc-kr");
        
        String removeString = "[^\uAC00-\uD7A3xfe0-9a-zA-Z\\s]";
        resultPost = resultPost.trim();
        resultPost = resultPost.replaceAll(removeString, "");
        resultPost = resultPost.replaceAll("\"", "");        
        resultPost = resultPost.replaceAll("\\p{Z}", "");
        resultPost = resultPost.replaceAll("\n", "");
        resultPost = resultPost.replaceAll("\t", "");
        resultPost = resultPost.replaceAll("\\n", "");
        resultPost = resultPost.replaceAll("\\t", "");
        resultPost = resultPost.replaceAll("\r", "");
        resultPost = resultPost.replaceAll("\\r", "");
        resultPost = resultPost.replaceAll("\r\n", "");
        resultPost = resultPost.replaceAll("\\r\\n", "");
        resultPost = resultPost.replaceAll(System.getProperty("line.separator"), "");
        logger.debug("resultPost replace:"+resultPost);
        
        if(resultPost.matches(".*ReturnResultValue00.*") || resultPost.matches(".*ReturnStatusValue00.*")){
            nmScreen = "정상접수";
        }else if(resultPost.matches(".*ReturnResultValue01.*") || resultPost.matches(".*ReturnStatusValue01.*")){
            nmScreen = "접수";
        }else if(resultPost.matches(".*ReturnResultValue02.*") || resultPost.matches(".*ReturnStatusValue02.*")){
            nmScreen = "심사";
        }else if(resultPost.matches(".*ReturnResultValue89.*") || resultPost.matches(".*ReturnStatusValue89.*")){
            nmScreen = "중복거절-6개월";
        }else if(resultPost.matches(".*ReturnResultValue10.*") || resultPost.matches(".*ReturnStatusValue10.*")){
            nmScreen = "거절";
        }else if(resultPost.matches(".*ReturnResultValue99.*") || resultPost.matches(".*ReturnStatusValue99.*")){
            nmScreen = "실패";
        }else if(resultPost.matches(".*ReturnResultValue91.*") || resultPost.matches(".*ReturnStatusValue91.*")){
            nmScreen = "실패-계약종료상품";
        }else if(resultPost.matches(".*ReturnResultValue92.*") || resultPost.matches(".*ReturnStatusValue92.*")){
            nmScreen = "실패-계약종료제휴사";
        }else if(resultPost.matches(".*ReturnResultValue12.*") || resultPost.matches(".*ReturnStatusValue12.*")){
            nmScreen = "취소";
        }else if(resultPost.matches(".*ReturnResultValue03.*") || resultPost.matches(".*ReturnStatusValue03.*")){
            nmScreen = "결제";
        }else if(resultPost.matches(".*ReturnResultValue04.*") || resultPost.matches(".*ReturnStatusValue04.*")){
            nmScreen = "승인";
        }else if(resultPost.matches(".*ReturnResultValue07.*") || resultPost.matches(".*ReturnStatusValue07.*")){
            nmScreen = "입금";
        }else if(resultPost.matches(".*ReturnResultValue13.*") || resultPost.matches(".*ReturnStatusValue13.*")){
            nmScreen = "보류";
        }else if(resultPost.matches(".*ReturnResultValue14.*") || resultPost.matches(".*ReturnStatusValue14.*")){
            nmScreen = "보정대기";
        }else if(resultPost.matches(".*ReturnResultValue66.*") || resultPost.matches(".*ReturnStatusValue66.*")){
            nmScreen = "휴지통";
        }else if(resultPost.matches(".*ReturnResultValue98.*") || resultPost.matches(".*ReturnStatusValue98.*")){
            nmScreen = "실패-핸드폰인증안된건";
        }else if(resultPost.matches(".*ReturnResultValue59.*") || resultPost.matches(".*ReturnStatusValue59.*")){
            nmScreen = "보증인정보누락";
        }else{
            nmScreen = "처리상태확인불가";
        }

        resultMemo = resultPost.substring(resultPost.length()-20);
        resultMemo = commonUtil.getHangul(resultMemo);
        bexMasterRequestVO.setNmScreen(nmScreen);
        bexMasterService.updateBexMaster(bexMasterRequestVO);
        bexMasterRequestVO.setNmScreen(nmScreen);
        bexMasterRequestVO.setDsCooperate(resultMemo);
        bexMasterService.insertBexContact(bexMasterRequestVO); 
        
        return resultCode;
    }
}
